---
version: 2
updates:
  - package-ecosystem: github-actions
    directories:
      - /
      - /.github/actions/setup-queens-pixi
    schedule:
      interval: monthly
    groups:
      github-actions:
        patterns:
          - "*"
    cooldown:
      default-days: 7
