default_stages: [pre-commit, pre-merge-commit, pre-push, manual]
repos:
  - repo: local
    hooks:
      - id: trailing-whitespace
        name: trim trailing whitespace
        entry: trailing-whitespace-fixer
        language: python
        types: [text]
      - id: end-of-file-fixer
        name: fix end of files
        entry: end-of-file-fixer
        language: python
        types: [text]
      - id: check-added-large-files
        name: check for added large files
        entry: check-added-large-files
        language: python
        types: [text]
      - id: check-license-header
        name: check for correct license header
        entry: licenseheaders
        args: ["-t", "license_header.tmpl", "--files"]
        language: python
        types: ["python"]
        pass_filenames: true
      - id: check-pyproject-dependency-integrity
        name: check pyproject dependency integrity
        entry: >
          python3 tools/dependencies/check_pyproject_dependency_integrity.py
          --allow-version-mismatch gpflow
          --path
        language: system
        files: '^pyproject\.toml$'
        pass_filenames: true
      - id: ruff-check
        name: ruff check
        entry: ruff check --fix --force-exclude
        language: system
        types_or: [ python, pyi, jupyter, pyproject ]
      - id: docformatter
        name: docformatter
        entry: docformatter
        args: [--in-place]
        language: python
        types: ["python"]
      - id: commitizen
        name: commitizen
        entry: cz
        args: ["check", "--commit-msg-file", ".git/COMMIT_EDITMSG"]
        pass_filenames: false
        language: system
        stages: [commit-msg, manual]
      - id: isort
        name: isort (python)
        entry: isort
        language: python
        always_run: false
        pass_filenames: true
        additional_dependencies: ["toml"]
      - id: black
        name: black
        entry: black
        language: python
        types: ["python"]
        always_run: false
        pass_filenames: true
        additional_dependencies: ["toml"]
      - id: yamllint
        name: yamllint
        entry: yamllint
        args:
          - -f=colored
        language: python
        types: ["yaml"]
      - id: pylint
        name: pylint
        entry: pylint
        language: python
        types: ["python"]
        additional_dependencies: ["toml"]
        always_run: false
        pass_filenames: true
        exclude: '^tests/integration_tests/'
      - id: pylint-integration-tests
        name: pylint (tests)
        entry: pylint --disable=duplicate-code
        language: python
        types: ["python"]
        additional_dependencies: ["toml"]
        always_run: false
        pass_filenames: true
        files: '^tests/integration_tests/'
      - id: mypy
        name: mypy (check type hinting)
        entry: mypy
        language: python
        types: ["python"]
        pass_filenames: true
        # Delete modules once type hinting has been introduced there
        exclude: |
          (?x)(
          ^(.gitlab|.github|config|doc|tests|test_utils)/|
          ^src/(example_simulator_functions|queens_interfaces)/|
          ^src/queens/(drivers|iterators|models)/|
          ^src/queens/(schedulers|stochastic_optimizers|visualization)/|
          ^src/queens/(main.py|global_settings.py)
          ).*$
      - id: nbstripout
        name: Strip outputs from Jupyter notebooks
        entry: nbstripout
        language: system
        files: \.ipynb$
